FROM composer:2 AS composer
FROM blackfire/blackfire:2 AS blackfire
FROM php:8.4-fpm-alpine

LABEL org.opencontainers.image.source=https://github.com/openaction/docker-php

ENV AMQP_VERSION=2.1.2 \
    APCU_VERSION=5.1.24 \
    REDIS_VERSION=6.2.0 \
    COMPOSER_ALLOW_SUPERUSER=1 \
    BLACKFIRE_AGENT_SOCKET=unix:///var/run/blackfire/agent.sock \
    BLACKFIRE_SOCKET=unix:///var/run/blackfire/agent.sock \
    BLACKFIRE_ENDPOINT=https://blackfire.io \
    BLACKFIRE_LOG_LEVEL=1 \
    BLACKFIRE_LOG_FILE= \
    BLACKFIRE_DISABLE_PCOV=1

COPY conf/install-blackfire.sh /usr/local/bin/install-blackfire
COPY conf/start-blackfire-agent.sh /usr/local/bin/start-blackfire-agent
COPY conf/start-php-fpm.sh /usr/local/bin/start-php-fpm

RUN apk add --no-cache --virtual .persistent-deps \
        curl \
        git \
        gmp-dev \
        icu-libs \
        icu-data-full \
        libpq \
        make \
        mysql-client \
        nano \
        nginx \
        postgresql-client \
        poppler \
        poppler-utils \
        supervisor \
        zlib

RUN set -xe \
    && chmod +x /usr/local/bin/install-blackfire /usr/local/bin/start-blackfire-agent /usr/local/bin/start-php-fpm \
    && apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        freetype \
        freetype-dev \
        gnu-libiconv \
        icu-dev \
        jpeg-dev \
        libpng \
        libpng-dev \
        libjpeg \
        libjpeg-turbo \
        libjpeg-turbo-dev \
        libwebp-dev \
        libxslt-dev \
        libzip-dev \
        postgresql-dev \
        rabbitmq-c-dev \
        sqlite-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-configure intl \
    && docker-php-ext-install \
        bcmath \
        exif \
        fileinfo \
        gd \
        gmp \
        intl \
        pcntl \
        pdo_mysql \
        pdo_pgsql \
        pdo_sqlite \
        xsl \
        zip \
    && pecl install \
        amqp-${AMQP_VERSION} \
        apcu-${APCU_VERSION} \
        redis-${REDIS_VERSION} \
        pcov \
    && docker-php-ext-enable --ini-name 75-amqp.ini amqp \
    && docker-php-ext-enable --ini-name 80-apcu.ini apcu \
    && docker-php-ext-enable --ini-name 85-redis.ini redis \
    && docker-php-ext-enable --ini-name 90-pcov.ini pcov \
    && install-blackfire \
    && runDeps="$( \
        scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
            | tr ',' '\n' \
            | sort -u \
            | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
    )" \
    && apk add --no-cache --virtual .php-phpexts-rundeps $runDeps \
    && apk del .build-deps \
    && mkdir -p /run/nginx/ \
    && mkdir /etc/periodic/1min

COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY --from=blackfire /usr/local/bin/blackfire /usr/local/bin/blackfire
COPY conf/php-dev.ini /usr/local/etc/php/php.ini
COPY conf/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY conf/supervisord.conf /usr/local/etc/supervisord.conf

RUN composer self-update

EXPOSE 80

WORKDIR /app
CMD ["supervisord", "--configuration", "/usr/local/etc/supervisord.conf"]
