[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:nginx]
command=/usr/sbin/nginx
priority=20
autostart=true
autorestart=true
redirect_stderr=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:blackfire-agent]
command=/usr/local/bin/start-blackfire-agent
priority=5
autostart=true
autorestart=unexpected
startsecs=0
exitcodes=0
redirect_stderr=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:php-fpm]
command=/usr/local/bin/start-php-fpm
priority=10
autostart=true
autorestart=true
redirect_stderr=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
