name: PHP 8.4

on:
    push:
        branches: ['8.4']

jobs:
    prod:
        runs-on: ubicloud-standard-4-ubuntu-2404
        steps:
            - uses: actions/checkout@v4

            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push console image
              env:
                  IMAGE: ghcr.io/${{ github.repository }}/prod
                  TAG: 8.4
              run: |
                  docker build -t "${IMAGE}:${TAG}" -f Dockerfile.prod .
                  docker push "${IMAGE}:${TAG}"

    dev:
        runs-on: ubicloud-standard-4-ubuntu-2404
        steps:
            - uses: actions/checkout@v4

            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push console image
              env:
                  IMAGE: ghcr.io/${{ github.repository }}/dev
                  TAG: 8.4
              run: |
                  docker build -t "${IMAGE}:${TAG}" -f Dockerfile.dev .
                  docker push "${IMAGE}:${TAG}"
