name: PHP 8.1

on:
    push:
        branches: ['8.1']

jobs:
    prod:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: ${{ github.repository }}/prod
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  registry: ghcr.io
                  dockerfile: Dockerfile.prod
                  tags: '8.1'

    dev:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: ${{ github.repository }}/dev
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  registry: ghcr.io
                  dockerfile: Dockerfile.dev
                  tags: '8.1'
